In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.feature_selection import RFE
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, PolynomialFeatures

import statsmodels.api as sm
from statsmodels.formula.api import ols

In [4]:
df = pd.read_csv('../../../data/Clean_data.csv')

In [5]:
df['coord'] = df['lat'] * df['long']
df.drop(['zipcode','lat','long'], axis=1, inplace=True)

In [6]:
df.dropna(inplace=True)

In [7]:
base_model = df.copy()

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)



In [8]:
model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)

[0.76214473 0.73950338 0.75503581 0.73725033 0.74748808]
-34218451592.19468


In [9]:
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)
y_test_scaled = scaler.transform(y_test)


In [10]:
model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)

[0.77164736 0.73953127 0.75505613 0.73833722 0.74748873]
-0.2500526377738525


to log X_data can't use anything with a zero



In [11]:
df_price_log = np.log(y_train) #['log_price']
df_price_log_test = np.log(y_test)

 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)
y_scaled_log_price_test = scaler.transform(df_price_log_test)


In [15]:
model_scaled_log_price = PolynomialFeatures(degree = 2)
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

#cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train,scoring = 'neg_mean_squared_error', cv=5)
#print(cv_results)
#cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train,scoring = 'neg_mean_squared_error' cv=5,  scoring='neg_mean_squared_error'))
#print(cv_results_mean_scaled_ylog)

PolynomialFeatures()

In [16]:
# calculate predictions on training and test sets
y_hat_train = model_scaled_log_price.predict(X_train_scaled)
y_hat_test = model_scaled_log_price.predict(X_test_scaled)

#compare MSE for the predicted training and test values 
train_mse = mean_squared_error(y_scaled_log_price_train, y_hat_train)
test_mse = mean_squared_error(y_scaled_log_price_test, y_hat_test)


print(train_mse)
print(test_mse)

AttributeError: 'PolynomialFeatures' object has no attribute 'predict'

[0.82096421 0.81406076 0.80113155 0.81273929 0.81141737]
-0.18784958406146018

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21242 entries, 0 to 21418
Data columns (total 46 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   price             21242 non-null  float64
 1   bedrooms          21242 non-null  float64
 2   bathrooms         21242 non-null  float64
 3   sqft_living       21242 non-null  float64
 4   sqft_lot          21242 non-null  float64
 5   floors            21242 non-null  float64
 6   waterfront        21242 non-null  int64  
 7   view              21242 non-null  float64
 8   condition         21242 non-null  float64
 9   grade             21242 non-null  float64
 10  sqft_above        21242 non-null  float64
 11  basement          21242 non-null  int64  
 12  yr_built          21242 non-null  float64
 13  yr_renovated      21242 non-null  float64
 14  lat               21242 non-null  float64
 15  long              21242 non-null  float64
 16  sqft_living15     21242 non-null  float6

TESTING SPLIT IN 2 LOW

In [11]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] < 9]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)




In [12]:
model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)

[0.6710213  0.69522063 0.69685286 0.67026612 0.67125703]
-12418445846.383966


In [13]:
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)




In [14]:
model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)

[0.67105391 0.69522054 0.6968378  0.67025889 0.67188672]
-0.3182915573487553


In [15]:
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

In [16]:
model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.72413614 0.73556896 0.73611268 0.7182319  0.71958568]
-0.273083365597513


LOWER SCORES OVERALL

BASE LINE TEST SPLIT HIGH GRADE

In [17]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] > 8]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)



In [18]:
model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)

[0.67002878 0.74361246 0.71374602 0.71780729 0.73467976]
-87905019629.65884


In [19]:
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)



In [20]:
model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)

[0.67001818 0.7435335  0.71368629 0.71781705 0.73469709]
-0.2827557049702945


In [21]:
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

In [22]:
model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.75929759 0.79268187 0.77898245 0.79652485 0.7925555 ]
-0.2152873002369923


ALSO LOWER THAN BASELINE

In [ ]:
BASELINE TEST SPLIT TOTAL 4

In [23]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 4]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

In [24]:
model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)

[-8.16252223 -0.23691345 -1.18968868 -2.72165453 -0.08391814]
-102665176004.01968


In [25]:
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)




In [26]:
model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)

[-9.43055136 -0.35574663 -0.84464161 -0.18815487 -0.85440257]
-2.032741013638147


In [27]:
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

In [28]:
model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[-3.96362306 -0.20415776 -0.35827914  0.12283194 -0.83151438]
-1.7911874337963627


ABSOLUTELY AWFUL, MOVING ON TOTAL SPLIT 5

In [29]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 5]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[-0.1017558  -0.09383212  0.01218587  0.2947682  -0.15125816]
-15730181929.528858
[-0.0515548  -0.12852018  0.0686805   0.28135763 -0.15125816]
-0.9706072014433458
[ 0.00654528  0.03470563  0.05697637  0.33165779 -0.01800349]
-0.8811024040586428


NOPE, NEXT TOTAL 6

In [30]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 6]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.40507473 0.47992618 0.5891721  0.48587888 0.4442934 ]
-11192715571.033558
[0.40491664 0.48010757 0.58663936 0.48314971 0.44430555]
-0.5178637877412853
[0.41142012 0.49345805 0.52719432 0.50918365 0.45828472]
-0.5180817865919072


BETTER THAN WITH GRADE 5, STILL AWFUL NEXT GRADE 7

In [31]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 7]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.59566218 0.65170218 0.60312171 0.64686288 0.64518194]
-9085130924.355366
[0.59568496 0.65179524 0.60310564 0.64684306 0.64531695]
-0.3700053329492114
[0.65043743 0.67976482 0.66168712 0.66891907 0.68454273]
-0.3303041130732579


IMPRESSIVELY NOT COMPLETELY AWFUL, BUT STILL WORSE THAN THE BASELINE, NEXT GRADE IS 8

In [32]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 8]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.41851534 0.64937437 0.68650257 0.62731022 0.4769717 ]
-17169212990.988342
[0.59654091 0.64938381 0.68650648 0.62736316 0.65062065]
-0.35469831835795146
[0.67373546 0.69412132 0.73512368 0.69721706 0.71820701]
-0.2952967348135324


MEH, NEXT GRADE 9

In [71]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 9|base_model['grade']==10]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.67635033 0.67920265 0.65310378 0.68060787 0.64342831]
-54720906616.684715
[0.67634788 0.67959929 0.65311929 0.68064543 0.64352702]
-0.3334295426468615
[0.75289802 0.76764188 0.72168513 0.75085244 0.73085334]
-0.2550178202230099


NEXT GRADE 10

In [34]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 10]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[0.70664125 0.63595264 0.58609086 0.69080137 0.67519263]
-81951705787.6537
[0.70600625 0.63623632 0.58608592 0.69046059 0.67492346]
-0.3416971879699595
[0.70769155 0.67106253 0.62331802 0.72571084 0.68145443]
-0.3178679015885566


IT'S GETTING WORSE NOW, NEXT GRADE 11

In [35]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 11]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[ 0.58337836  0.67017376 -1.69055276  0.24483817 -0.73546256]
-226889880560.369
[ 5.83707733e-01  6.68963365e-01 -1.80516963e+23  3.25189540e-01
 -1.29192803e+22]
-2.6882725350643006e+22
[ 4.86605798e-01  6.59135621e-01 -4.13464607e+22  5.57292627e-01
 -1.84285250e+22]
-1.1364323299639647e+22


THAT"S A NO FROM ME, NEXT GRADE 12

In [36]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 12]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[-5.338245    0.30870341 -1.62182501 -9.64923553  0.34502945]
-879307300674.428
[ -4.59282677   0.30870341  -1.62182501 -10.6787304    0.34502945]
-2.1180384284222145
[-2.16909421  0.30053686 -0.26993142 -0.95680387  0.28382544]
-1.2270162660735415


NOPE FINAL CHANCE TO PROVE A SPLIT WORKS GRADE 13

In [37]:
base_model = df.copy()

base_model = base_model.loc[base_model['grade'] == 13]

X , y = base_model.drop(columns=['price']), base_model[['price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)

model1 = LinearRegression()
model1.fit(X_train, y_train)

# train_preds = model1.predict(X_train)
# y_train == train_preds 

test_preds = model1.predict(X_test)

cv_results = cross_val_score(model1, X_train, y_train, cv=5)
print(cv_results)
cv_results_mean = np.mean(cross_val_score(model1, X, y, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean)
#model1.score(y_test, test_preds)
scaler = StandardScaler()
# Calculate the standard deviation of the X_train dataset
scaler.fit(X_train)
# convert all values into their standard deviation equivalents.
X_train_scaled = scaler.transform(X_train)

scaler.fit(y_train)
y_train_scaled = scaler.transform(y_train)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)

# train_preds = model_scaled.predict(X_train)
test_preds_scaled = model_scaled.predict(X_train_scaled)

cv_results_scaled = cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5)
print(cv_results_scaled)
cv_results_mean_scaled = np.mean(cross_val_score(model_scaled, X_train_scaled, y_train_scaled, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled)
#model_scaled.score(test_preds, y_test)
df_price_log = np.log(y_train) #['log_price']
 
scaler.fit(df_price_log)
y_scaled_log_price_train = scaler.transform(df_price_log)

model_scaled_log_price = LinearRegression()
model_scaled_log_price.fit(X_train_scaled, y_scaled_log_price_train)

# train_preds = model_scaled.predict(X_train)
#test_preds = model_scaled.predict(X_test_scaled)

cv_results = cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5)
print(cv_results)
cv_results_mean_scaled_ylog = np.mean(cross_val_score(model_scaled_log_price, X_train_scaled, y_scaled_log_price_train, cv=5,  scoring='neg_mean_squared_error'))
print(cv_results_mean_scaled_ylog)

[-14.0018192    0.94173119   0.94745276  -0.30019202          nan]
-63164076740601.94
[-7.27496615  0.67500802  0.03089859 -0.11987703         nan]
-0.5869332533875065
[-8.06788585  0.56908528  0.2798255   0.57974253         nan]
-0.5235207426226826


/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


DIDN"T THINK SO